/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#003857",
        "on-primary": "#ffffff",
        "primary-container": "#1b4f72",
        "on-primary-container": "#92c0e9",
        "primary-fixed": "#cce5ff",
        "primary-fixed-dim": "#9dcbf4",
        "secondary": "#4e6076",
        "on-secondary": "#ffffff",
        "secondary-container": "#cfe1fc",
        "on-secondary-container": "#52647a",
        "secondary-fixed": "#d1e4fe",
        "secondary-fixed-dim": "#b6c8e2",
        "tertiary": "#163653",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2f4d6b",
        "on-tertiary-container": "#a0bee0",
        "tertiary-fixed": "#cfe4ff",
        "tertiary-fixed-dim": "#abc9ec",
        "background": "#f7f9ff",
        "on-background": "#111d28",
        "surface": "#f7f9ff",
        "on-surface": "#111d28",
        "surface-variant": "#d7e4f4",
        "on-surface-variant": "#41474e",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf4ff",
        "surface-container": "#e3efff",
        "surface-container-high": "#dde9f9",
        "surface-container-highest": "#d7e4f4",
        "surface-bright": "#f7f9ff",
        "surface-dim": "#cfdbeb",
        "surface-tint": "#326286",
        "outline": "#72787f",
        "outline-variant": "#c1c7cf",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      spacing: {
        "space-2xs": "2px",
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "12px",
        "space-lg": "16px",
        "space-xl": "24px",
        "space-2xl": "32px",
        "nav-height": "48px",
        "panel-width-sm": "320px",
        "panel-width-md": "420px",
        "panel-width-lg": "560px",
        "timeline-height": "72px",
      },
      fontFamily: {
        body: ["IBM Plex Sans", "sans-serif"],
        heading: ["IBM Plex Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
      }
    },
  },
  plugins: [],
}
